branches:
  - master
  - release

build:
  image: php
  commands:
    - 'make syntax.checker'
    # Build release
    - 'apt-get update'
    - 'apt-get -y install zip'
    - 'make zip'

deploy:
  rsync:
    user: $$DEPLOY_USER
    host: prestashop.aplazame.com
    target: $$RELEASE_PATH
    source: aplazame
    delete: true
    recursive: true

  s3:
    acl: public-read
    region: $$S3_REGION
    bucket: $$S3_BUCKET
    access_key: $$S3_ACCESS_KEY
    secret_key: $$S3_SECRET_KEY
    source: latest.zip
    target: /modules/prestashop/aplazame.latest.zip
    recursive: false
    when:
      branch: release

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'drone'
    channel: 'developers'
    when:
      success: false
      failure: true
      change: true

  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASS
    recipients:
      - dev@aplazame.com
    when:
      success: false
      failure: true
      change: true
