image: python

branches:
  - master

script:
  - chmod +x ./.drone/*.sh
  - ./.drone/build.sh

deploy:
  bash:
    script:
      - ./.drone/deploy.sh
    when:
      branch: master

publish:
  s3:
    acl: public-read
    region: "eu-central-1"
    bucket: "aplazame.s3-website.eu-central-1.amazonaws.com"
    access_key: $$S3_ACCESS_KEY
    secret_key: $$S3_SECRET_KEY
    source: latest.zip
    target: /modules/prestahop
    recursive: false
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'prestashop'
    on_success: change
    on_failure: true

  email:
    recipients:
      - dev@aplazame.com
    on_success: change
    on_failure: true
