version: "2"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    environment:
      - ADMIN_MAIL=demo@prestashop.com
      - ADMIN_PASSWD=prestashop_demo
      - PS_DEV_MODE=1
      - PS_COUNTRY=ES
      - PS_DOMAIN=prestashop.aplazame
      - PS_ERASE_DB=1
      - PS_FOLDER_ADMIN=adminTest
      - PS_FOLDER_INSTALL=installTest
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_INSTALL_AUTO=1
      - PS_LANGUAGE=es
      - DB_SERVER=db
      - DB_PASSWD=password
    volumes:
      - prestashop:/var/www/html
      - ./aplazame:/var/www/html/modules/aplazame
    ports:
      - "80:80"

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=prestashop
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:
  prestashop:
